# Generated by Django 4.2.1 on 2023-07-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firsrtapp", "0002_remove_user_name_remove_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="username",
        ),
    ]
