# Generated by Django 4.2.1 on 2023-07-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firsrtapp", "0003_rename_phone_number_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruits",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
